### ISSUE TITLE
Not generating required output

### ISSUE THREAD

**Issue by usmanali-arshi** [wangcongcong123/auto_coding#10]
When I try to input : "def factorial", it gives me the following error. Could you please help me resolve it? Thanks. 

File "interact.py", line 52, in <module>
    outputs = model.generate(input_ids=input_ids.to("cuda") if args.use_cuda else input_ids,
  File "/home/ua383/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 575, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPT2LMHeadModel' object has no attribute 'generate'

**Comment by wangcongcong123** [comment]
Have you tried down-version the transformers?

**Comment by usmanali-arshi** [comment]
Thanks for getting back to me. I've managed to run it but when I try to fine-tune it on your dataset it gives me this error:
Traceback (most recent call last):
  File "train.py", line 83, in <module>
    model_trainer = ModelTrainer(model,
  File "/home/ua383/work/auto_coding/trainer.py", line 328, in __init__
    self._optimizer = optimizer_class(optimizer_grouped_parameters, **optimizer_params)
  File "/home/ua383/anaconda3/envs/training/lib/python3.8/site-packages/transformers/optimization.py", line 301, in __init__
    require_version("torch>=1.5.0")  # add_ with alpha
  File "/home/ua383/anaconda3/envs/training/lib/python3.8/site-packages/transformers/utils/versions.py", line 114, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/home/ua383/anaconda3/envs/training/lib/python3.8/site-packages/transformers/utils/versions.py", line 49, in _compare_versions
    raise ImportError(
ImportError: torch>=1.5.0 is required for a normal functioning of this module, but found torch==1.4.0.

Although I tried installing torch>=1.5.0 versions, it still gives me the same error. Could you please help me with this issue. Thanks.

**Comment by Penguin-jpg** [comment]
> When I try to input : "def factorial", it gives me the following error. Could you please help me resolve it? Thanks.
> 
> File "interact.py", line 52, in outputs = model.generate(input_ids=input_ids.to("cuda") if args.use_cuda else input_ids, File "/home/ua383/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 575, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'GPT2LMHeadModel' object has no attribute 'generate'

Try using transformers 3.5.0. It works for me.

**Comment by vishalsingha** [comment]
Try installing torch>=1.5 using the below code after uninstalling it

```!pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html```
